# .github/workflows/render.yml
name: Video Render Pipeline
on:
  workflow_dispatch:
    inputs:
      audio:
        description: 'Audio URL'
        required: true
      captions:
        description: 'JSON array of captions'
        required: true
      images:
        description: 'JSON array of image URLs'
        required: true
      captionStyle:
        description: 'JSON caption styles'
        required: true

permissions:
  contents: write
  actions: write
  id-token: write

jobs:
  render:
    runs-on: ubuntu-latest
    timeout-minutes: 25  # Increased timeout
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for action resolution

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev libnss3 libgtk-3-0 libxss1 \
            libasound2 fonts-liberation libdrm2 libxkbcommon0 \
            libgl1-mesa-glx

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci --production

      - name: Render Video
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: |
          mkdir -p out
          npx remotion render src/index.js Main out/video.mp4 \
            --props="${{ toJson(inputs) }}" \
            --concurrency=2 \
            --quality=80 \
            --scale=0.8 \
            --timeout=300000 \
            --log=verbose

      - name: Verify Output File
        run: |
          ls -lh out/
          [ -f out/video.mp4 ] || (echo "Missing rendered video" && exit 1)

      - name: Upload to Cloudinary
        uses: jakejarvis/cloudinary-upload-action@d002a4e # Fixed commit hash
        with:
          cloud_name: ${{ secrets.CLOUDINARY_CLOUD }}
          api_key: ${{ secrets.CLOUDINARY_KEY }}
          api_secret: ${{ secrets.CLOUDINARY_SECRET }}
          folder: renders
          files: out/video.mp4
          upload_preset: unsigned
          overwrite: true