name: Video Render Pipeline
on:
  workflow_dispatch:
    inputs:
      audio:
        description: 'Audio URL'
        required: true
      captions:
        description: 'JSON array of captions'
        required: true
      images:
        description: 'JSON array of image URLs'
        required: true
      captionStyle:
        description: 'JSON caption styles'
        required: true

permissions:
  contents: read

jobs:
  render:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev libnss3 libgtk-3-0 libxss1 \
            libasound2 fonts-liberation libdrm2 libxkbcommon0 \
            libgl1-mesa-glx

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci --production

      - name: Render Video
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: |
          mkdir -p out
          npx remotion render src/index.js Main out/video.mp4 \
            --props="${{ toJson(inputs) }}" \
            --concurrency=2 \
            --quality=80 \
            --scale=0.8 \
            --timeout=300000

      - name: Upload to Express Server
        run: |
          curl -X POST \
            -H "Authorization: Bearer Sumitsingh61220" \
            -F "video=@out/video.mp4" \
            "http://localhost:4000/upload"